<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>080fe3a4-624b-42ea-8db1-e8203d277f60</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Accenture-Assessment.ApiService\Accenture-Assessment.ApiService.csproj" />
    <ProjectReference Include="..\Accenture-Assessment.Web\Accenture-Assessment.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.5.0" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="9.5.2" />
  </ItemGroup>

</Project>
