<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Accenture-Assessment.Data\Accenture-Assessment.Data.csproj" />
    <ProjectReference Include="..\Accenture-Assessment.ServiceDefaults\Accenture-Assessment.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="9.5.2" />
	  <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="9.0.0" />
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.10" />
  </ItemGroup>

</Project>
